# Generated by Django 2.2.3 on 2019-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190707_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='삭제된 유저의 이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='삭제된 유저의 username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
