# Generated by Django 2.2.2 on 2019-06-29 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='스터디명')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='설명')),
            ],
            options={
                'verbose_name': '스터디',
                'verbose_name_plural': '스터디 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '스터디 카테고리',
                'verbose_name_plural': '스터디 카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.CharField(choices=[('normal', '일반멤버'), ('sub_manager', '부 관리자'), ('manager', '관리자')], default='normal', max_length=12, verbose_name='역할')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_member_set', to='study.Study', verbose_name='스터디')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_member_set', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '스터디 멤버',
                'verbose_name_plural': '스터디 멤버 목록',
            },
        ),
        migrations.AddField(
            model_name='study',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_set', to='study.StudyCategory', verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='장소')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='설명')),
                ('date', models.DateField(verbose_name='일정 당일')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_set', to='study.Study', verbose_name='스터디')),
            ],
            options={
                'verbose_name': '스터디 일정',
                'verbose_name_plural': '스터디 일정 목록',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vote', models.CharField(choices=[('attend', '참석'), ('late', '지각'), ('absent', '결석')], max_length=10, verbose_name='사전 참석 투표')),
                ('att', models.CharField(choices=[('attend', '참석'), ('late', '지각'), ('absent', '결석')], max_length=10, verbose_name='실제 참석 결과')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='study.Schedule', verbose_name='스터디 일정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '스터디 일정 참가',
                'verbose_name_plural': '스터디 일정 참가 목록',
            },
        ),
    ]
