# Generated by Django 2.2.2 on 2019-06-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_set', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att',
            field=models.CharField(blank=True, choices=[('attend', '참석'), ('late', '지각'), ('absent', '결석')], max_length=10, verbose_name='실제 참석 결과'),
        ),
    ]
