# Generated by Django 2.2.3 on 2019-07-16 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studymember_is_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='주제'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='vote',
            field=models.CharField(blank=True, choices=[('attend', '참석'), ('late', '지각'), ('absent', '결석')], max_length=10, verbose_name='사전 참석 투표'),
        ),
        migrations.AlterField(
            model_name='study',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_set', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.CreateModel(
            name='StudyInviteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='초대코드')),
                ('duration', models.PositiveSmallIntegerField(default=24, verbose_name='유효시간')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Study', verbose_name='스터디')),
            ],
            options={
                'verbose_name': '스터디 초대 링크',
                'verbose_name_plural': '스터디 초대 링크 목록',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='studyinvitelink',
            index=models.Index(fields=['created'], name='study_study_created_73d952_idx'),
        ),
        migrations.AddIndex(
            model_name='studyinvitelink',
            index=models.Index(fields=['modified'], name='study_study_modifie_81a258_idx'),
        ),
    ]
