# Generated by Django 2.2.2 on 2019-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20190718_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='due_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='스터디 시작 일시'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='studying_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='스터디 시간'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='vote_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='투표 종료 일시'),
        ),
    ]
