# Generated by Django 2.2.3 on 2019-07-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20190719_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='studying_time',
        ),
    ]
