# Generated by Django 2.2.3 on 2019-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_remove_schedule_studying_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='studying_time',
            field=models.TimeField(blank=True, null=True, verbose_name='스터디 시간'),
        ),
    ]
