# Generated by Django 2.2.2 on 2019-08-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20190724_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='아이콘 이미지')),
            ],
            options={
                'verbose_name': '스터디 아이콘',
                'verbose_name_plural': '스터디 아이콘 목록',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='study',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_set', to='study.StudyIcon', verbose_name='아이콘'),
        ),
    ]
