# Generated by Django 2.2.4 on 2019-08-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20190813_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinvitetoken',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='study.Study', verbose_name='스터디'),
        ),
        migrations.AlterField(
            model_name='studymembership',
            name='role',
            field=models.CharField(choices=[('normal', '스터디 멤버'), ('sub_manager', '스터디 서브 리더'), ('manager', '스터디 리더')], default='normal', max_length=12, verbose_name='역할'),
        ),
    ]
